// <auto-generated />
using System;
using AHM.Audit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AHM.Audit.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260626095403_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AHM.Audit.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AhmOfficer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AircraftRecertified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C2_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_IdealTrim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_Inflight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_Landing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_TakeOff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_ZeroFuel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C7_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectionTicket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectionsMade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("D1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D5_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D5_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D6_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabasePrintout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("E1_DOW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MLAW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MRW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MTOW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MZFW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E2_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E2_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E3_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("G1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("LIR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonForRecertification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisionUpdate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisionUpdates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("AHM.Audit.Models.AuditoriaArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AhmOfficer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AircraftRecertified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArchiveYear")
                        .HasColumnType("integer");

                    b.Property<string>("B1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C2_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_IdealTrim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_Inflight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_Landing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_TakeOff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C4_ZeroFuel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("C7_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectionTicket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectionsMade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("D1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D5_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D5_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("D6_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabasePrintout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("E1_DOW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MLAW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MRW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MTOW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E1_MZFW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E2_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E2_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("E3_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("G1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LIR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonForRecertification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisionUpdate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisionUpdates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaArchives");
                });

            modelBuilder.Entity("AHM.Audit.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AHM.Audit.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
